### ISSUE TITLE
Failed to create a PhysX CUDA Context Manager. Falling back to CPU.

### ISSUE THREAD

**Issue by HIT-ZY** [roboterax/humanoid-gym#18]
运行python train的命令报一下错误：
[Warning] [carb.gym.plugin] Failed to create a PhysX CUDA Context Manager. Falling back to CPU.
Physics Engine: PhysX
Physics Device: cpu
GPU Pipeline: disabled
/home/eit-robot2/anaconda3/envs/humanoid/lib/python3.8/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1670525541702/work/aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
[Error] [carb.gym.plugin] Gym cuda error: invalid resource handle: ../../../source/plugins/carb/gym/impl/Gym/GymPhysX.cpp: 6137
[Error] [carb.gym.plugin] Must enable GPU pipeline to use state tensors
[Error] [carb.gym.plugin] Must enable GPU pipeline to use state tensors
Traceback (most recent call last):
  File "scripts/train.py", line 43, in <module>
    train(args)
  File "scripts/train.py", line 37, in train
    env, env_cfg = task_registry.make_env(name=args.task, args=args)
  File "/home/eit-robot2/Documents/humanoid-gym/humanoid/utils/task_registry.py", line 97, in make_env
    env = task_class(   cfg=env_cfg,
  File "/home/eit-robot2/Documents/humanoid-gym/humanoid/envs/custom/humanoid_env.py", line 78, in __init__
    super().__init__(cfg, sim_params, physics_engine, sim_device, headless)
  File "/home/eit-robot2/Documents/humanoid-gym/humanoid/envs/base/legged_robot.py", line 80, in __init__
    self._init_buffers()
  File "/home/eit-robot2/Documents/humanoid-gym/humanoid/envs/base/legged_robot.py", line 452, in _init_buffers
    self.base_euler_xyz = get_euler_xyz_tensor(self.base_quat)
  File "/home/eit-robot2/Documents/humanoid-gym/humanoid/envs/base/legged_robot.py", line 51, in get_euler_xyz_tensor
    r, p, w = get_euler_xyz(quat)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: CUDA driver error: an illegal memory access was encountered
感觉是没用上cuda，请大佬帮忙看看

**Comment by zlw21gxy** [comment]
Could you operate the IsaacGym example? Additionally, could you verify whether a GPU can be identified in PyTorch? A general recommendation: Examine these two aspects initially. Kindly furnish more testing outcomes if the issue persists.

**Comment by Yzw-Camellia** [comment]
请问您解决这个报错了吗？我也出现了这个错误，但是不知道为什么

**Comment by 242726Yuncheng** [comment]
import torch
print(torch.cuda.is_available())
如果是true的话可能是因为没有检测到cuda，是用的wsl吗

**Comment by JayFu007** [comment]
> import torch print(torch.cuda.is_available()) 如果是true的话可能是因为没有检测到cuda，是用的wsl吗

是的，我用的wsl2它发生了这个报错，但是在wsl2中import torch，输入print(torch.cuda.is_available())，其返回值是true

**Comment by YanYichao** [comment]
> > import torch print(torch.cuda.is_available()) 如果是true的话可能是因为没有检测到cuda，是用的wsl吗
> 
> 是的，我用的wsl2它发生了这个报错，但是在wsl2中import torch，输入print(torch.cuda.is_available())，其返回值是true

同样有这个问题，请问有人解决了吗

**Comment by zlw21gxy** [comment]
We haven't tested the setup on WSL2, and using CUDA with WSL is generally not recommended due to potential compatibility and performance issues. We suggest using Ubuntu 20.04 or 22.04, as those are the platforms we've tested and validated. If you must use Windows, consider setting up a dual-boot system for better reliability.
